# Labeler configuration
# Label PRs based on changed files
# v5 format

backend:
  - changed-files:
      - any-glob-to-any-file:
          - "app/**/*"
          - "tests/**/*"
          - "pyproject.toml"
          - "uv.lock"

frontend:
  - changed-files:
      - any-glob-to-any-file:
          - "frontend/**/*"

infrastructure:
  - changed-files:
      - any-glob-to-any-file:
          - "k8s/**/*"
          - "docker-compose*.yml"
          - "**/Dockerfile"
          - "nginx*.conf"

ci/cd:
  - changed-files:
      - any-glob-to-any-file:
          - ".github/workflows/**/*"
          - ".github/actions/**/*"

documentation:
  - changed-files:
      - any-glob-to-any-file:
          - "**/*.md"
          - "docs/**/*"

dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - "package*.json"
          - "pyproject.toml"
          - "uv.lock"
          - "**/requirements*.txt"

security:
  - changed-files:
      - any-glob-to-any-file:
          - ".github/workflows/security-scan.yml"
          - "SECURITY.md"

configuration:
  - changed-files:
      - any-glob-to-any-file:
          - "*.toml"
          - "*.yaml"
          - "*.yml"
          - ".env.example"
          - ".gitignore"
