# Labeler configuration
# Label PRs based on changed files

backend:
  - "app/**/*"
  - "tests/**/*"
  - "pyproject.toml"
  - "uv.lock"

frontend:
  - "frontend/**/*"

infrastructure:
  - "k8s/**/*"
  - "docker-compose*.yml"
  - "**/Dockerfile"
  - "nginx*.conf"

ci/cd:
  - ".github/workflows/**/*"
  - ".github/actions/**/*"

documentation:
  - "**/*.md"
  - "docs/**/*"

dependencies:
  - "package*.json"
  - "pyproject.toml"
  - "uv.lock"
  - "**/requirements*.txt"

security:
  - ".github/workflows/security-scan.yml"
  - "SECURITY.md"

configuration:
  - "*.toml"
  - "*.yaml"
  - "*.yml"
  - ".env.example"
  - ".gitignore"
